import { cp, mkdir, mkdtemp, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { assertLinkFree, installedPackageVersion, installedSelfVersion, localGitDirty, localGitHead, requirementCommit, requirementPin, treeFingerprint } from "./inspect.js";
import { resolveGitHead, resolveGitRelease, resolveNpmRelease, resolvePypiRelease } from "./resolve.js";
import { AdapterError, fail, isCommit, runOrFail } from "./util.js";

/** Write the schema-1 result the Go checker reads back. */
export async function writeCheckResult(path, result) {
  if (!path) fail("OPENCODE_UPDATER_CHECK_RESULT is not set");
  await writeFile(path, `${JSON.stringify({ schemaVersion: 1, ...result }, null, 2)}\n`, "utf8");
}

export function statusFor(current, latest) {
  return current === latest ? "current" : "update-available";
}

/** Check a component whose identity is the remote default-branch HEAD. */
export async function checkGitHead({ target, remote, sourceSubdir = "" }) {
  const root = sourceSubdir ? join(target, sourceSubdir) : target;
  const current = await localGitHead(root);
  if (!current) fail(`${root} is not a git checkout`);
  if (await localGitDirty(root)) {
    return { status: "manual-only", summary: "Dirty git worktree", current };
  }
  const latest = await resolveGitHead(remote);
  return {
    status: statusFor(current, latest),
    summary: current === latest ? current : `${current} -> ${latest}`,
    current,
    latest,
    sourceCommit: latest,
  };
}

/**
 * Check a Python component pinned to an exact git commit inside requirements.in.
 */
export async function checkRequirementCommit({ target, remote, distribution }) {
  const requirements = join(target, "requirements.in");
  const current = await requirementCommit(requirements, distribution);
  if (!current) fail(`${requirements} has no exact commit pin for ${distribution}`);
  const latest = await resolveGitHead(remote);
  return {
    status: statusFor(current, latest),
    summary: current === latest ? current : `${current} -> ${latest}`,
    current,
    latest,
    sourceCommit: latest,
  };
}

/**
 * Check a Python component pinned to a git release tag. Identity is the commit
 * the tag points at, so a moving branch cannot change what gets installed.
 */
export async function checkRequirementRelease({ target, remote, distribution }) {
  const requirements = join(target, "requirements.in");
  const current = await requirementCommit(requirements, distribution);
  if (!current) fail(`${requirements} has no exact commit pin for ${distribution}`);
  const { tag, commit } = await resolveGitRelease(remote);
  return {
    status: statusFor(current, commit),
    summary: current === commit ? `${tag} (${current})` : `${current} -> ${commit} (${tag})`,
    current,
    latest: commit,
    sourceCommit: commit,
  };
}

/** Check a Python component pinned to a published PyPI version. */
export async function checkPypiRelease({ target, distribution }) {
  const requirements = join(target, "requirements.in");
  const current = await requirementPin(requirements, distribution);
  if (!current) fail(`${requirements} has no exact version pin for ${distribution}`);
  const { version, artifact } = await resolvePypiRelease(distribution);
  return {
    status: statusFor(current, version),
    summary: current === version ? current : `${current} -> ${version}`,
    current,
    latest: version,
    artifact,
  };
}

/**
 * Check an npm component. Identity is the published version plus its tarball
 * integrity; the recorded commit is provenance only.
 */
export async function checkNpmRelease({ target, packageName, manifest = "package.json", self = false }) {
  const manifestPath = join(target, manifest);
  const current = self ? await installedSelfVersion(manifestPath) : await installedPackageVersion(manifestPath, packageName);
  if (!current) fail(`${manifestPath} has no exact installed version for ${packageName}`);
  const { version, artifact, sourceCommit } = await resolveNpmRelease(packageName);
  return {
    status: statusFor(current, version),
    summary: current === version ? current : `${current} -> ${version}`,
    current,
    latest: version,
    artifact,
    sourceCommit,
  };
}

/**
 * Check Cheat Engine. Reports an update whenever the canonical source is behind
 * upstream OR the generated Windows mirror has drifted, because the mirror is
 * regenerated by the same update command.
 */
export async function checkCheatEngine({ target, remote, mirror }) {
  const source = join(target, "source");
  const current = await localGitHead(source);
  if (!current) fail(`${source} is not a git checkout`);
  if (await localGitDirty(source)) {
    return { status: "manual-only", summary: "Dirty git worktree", current };
  }
  const latest = await resolveGitHead(remote);
  const drift = await mirrorDrift(join(source, "MCP_Server"), mirror);
  if (current === latest && !drift) {
    return { status: "current", summary: current, current, latest, sourceCommit: latest };
  }
  return {
    // A drift-only resync keeps current === latest: the planner accepts that and
    // the update command regenerates the mirror from the staged source.
    status: "update-available",
    summary: current === latest ? `${current} (mirror resync)` : `${current} -> ${latest}`,
    current,
    latest,
    sourceCommit: latest,
  };
}

async function mirrorDrift(canonical, mirror) {
  try {
    const [left, right] = await Promise.all([treeFingerprint(canonical), treeFingerprint(mirror)]);
    return left.digest !== right.digest;
  } catch (error) {
    if (error?.code === "ENOENT") return true;
    throw error;
  }
}

/**
 * Check out an exact commit into the stage. Verifies the checked-out HEAD so a
 * remote that moved between check and stage cannot smuggle in other code.
 */
export async function stageGitCommit({ stage, remote, commit, name = "source" }) {
  if (!isCommit(commit)) fail(`refusing to stage a non-exact commit: ${commit}`);
  const destination = join(stage, name);
  await mkdir(destination, { recursive: true });
  await runOrFail(["git", "init", "--quiet", destination]);
  await runOrFail(["git", "-C", destination, "remote", "add", "origin", remote]);
  await runOrFail(["git", "-C", destination, "fetch", "--quiet", "--depth", "1", "origin", commit], { timeoutMs: 900_000 });
  await runOrFail(["git", "-C", destination, "checkout", "--quiet", "--detach", "FETCH_HEAD"]);
  const head = (await runOrFail(["git", "-C", destination, "rev-parse", "HEAD"])).toLowerCase();
  if (head !== commit) fail(`staged commit ${head} does not match the planned commit ${commit}`);
  return destination;
}

/**
 * Replace the generated Windows mirror with a fresh copy of the staged source.
 *
 * The new tree is built and verified beside the mirror before anything is
 * removed, so a failed copy leaves the existing mirror untouched. The temporary
 * backup is deleted only after the replacement is verified.
 */
export async function replaceMirror({ sourceDir, mirror, runId }) {
  const parent = dirname(mirror);
  await mkdir(parent, { recursive: true });
  const staged = join(parent, `.MCP_Server-stage-${runId}`);
  const backup = join(parent, `.MCP_Server-backup-${runId}`);
  await rm(staged, { recursive: true, force: true });
  await rm(backup, { recursive: true, force: true });

  await cp(sourceDir, staged, { recursive: true, dereference: false, preserveTimestamps: true });
  await assertNoGit(staged);
  const [expected, actual] = await Promise.all([treeFingerprint(sourceDir), treeFingerprint(staged)]);
  if (expected.digest !== actual.digest) fail("staged mirror does not match the canonical source");

  let restored = false;
  const existing = await pathExists(mirror);
  if (existing) await rename(mirror, backup);
  try {
    await rename(staged, mirror);
  } catch (error) {
    if (existing) {
      await rename(backup, mirror);
      restored = true;
    }
    throw error;
  }
  const verified = await treeFingerprint(mirror);
  if (verified.digest !== expected.digest) {
    if (existing && !restored) {
      await rm(mirror, { recursive: true, force: true });
      await rename(backup, mirror);
    }
    fail("mirror verification failed after replacement");
  }
  await rm(backup, { recursive: true, force: true });
  return { files: verified.count };
}

async function assertNoGit(root) {
  for (const entry of await readdir(root, { withFileTypes: true })) {
    if (entry.name === ".git") fail(`mirror must not contain .git: ${join(root, entry.name)}`);
    if (entry.isDirectory()) await assertNoGit(join(root, entry.name));
  }
}

async function pathExists(path) {
  try {
    await readdir(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    if (error?.code === "ENOTDIR") return true;
    throw error;
  }
}

/** Write the stage manifest that binds staged paths to this exact plan. */
export async function writeManifest({ manifestPath, planSha256, paths }) {
  if (!manifestPath) fail("OPENCODE_UPDATER_MANIFEST is not set");
  if (!planSha256) fail("OPENCODE_UPDATER_PLAN_SHA256 is not set");
  if (!Array.isArray(paths) || paths.length === 0) fail("manifest requires at least one path");
  const manifest = { schemaVersion: 2, planSha256, paths };
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  return manifest;
}

export async function withTempDir(prefix, callback) {
  const directory = await mkdtemp(join(tmpdir(), prefix));
  try {
    return await callback(directory);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

export { assertLinkFree, AdapterError, fail, readFile, resolve };
